---
# tasks file for monitor

- name: Create data directory for prometheus
  file:
    state: directory
    path: "{{ source_data_prom }}"
    mode: 0777

- name: Create data directory for Graphana
  file:
    state: directory
    path: "{{ source_data_grafana }}"
    mode: 0777

- name: uplodad docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ source_data_prom }}/docker-compose.yml"

- name: upload prometheus file
  template:
    src: prometheus.yml.j2
    dest: "{{ source_data_prom }}/prometheus.yml"

- name: Run docker compose
  docker_stack:
    state: present
    name: monitor
    compose:
      - "{{ source_data_prom }}docker-compose.yml"
  when: inventory_hostname == groups['docker_swarm_manager'][0]

- debug:
    var: output
