---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: molecule-swarm-1
    image: asg1612/docker-systemd
    privileged: true
    required: 'True'
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
    published_ports:
      - 0.0.0.0:9090:9090/tcp
      - 0.0.0.0:3000:3000/tcp
      - 0.0.0.0:80:80/tcp
      - 0.0.0.0:443:443/tcp
      - 0.0.0.0:8080:8080/tcp
    groups:
      - docker_swarm_manager
  - name: molecule-swarm-2
    image: asg1612/docker-systemd
    privileged: true
    required: 'True'
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
    groups:
      - docker_swarm_worker
  - name: molecule-swarm-3
    image: asg1612/docker-systemd
    privileged: true
    required: 'True'
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /lib/systemd/systemd
    groups:
      - docker_swarm_worker
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
