---
- name: Converge
  hosts: all
  vars:
    docker_version: 18.06.*
    source_data_prom: /data/prom/
    target_data_prom: /prometheus/
    source_data_grafana: /data/graf
    prom_dns: "monitor-prometheus.docker.localhost"
    grafana_dns: "monitor-grafana.docker.localhost"
    GF_SERVER_ROOT_URL: "http://monitor-prometheus.docker.localhost"
    GF_SERVER_DOMAIN: "monitor-prometheus.docker.localhost"
    GF_SECURITY_ADMIN_PASSWORD: "secret"
    prometheus_metrics: true
    consul_ip: false
  roles:
    - role: asg1612.docker
    - role: asg1612.dockerswarm
    - role: asg1612.traefik
    - role: monitor
